export enum FailureCode {
  INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",
  CURRENCY_MISMATCH = "CURRENCY_MISMATCH",
  REFERENCE_NOT_FOUND = "REFERENCE_NOT_FOUND",
  INVALID_REFERENCE_KIND = "INVALID_REFERENCE_KIND",
  REFERENCE_ALREADY_REVERSED = "REFERENCE_ALREADY_REVERSED",
  IDEMPOTENCY_KEY_CONFLICT = "IDEMPOTENCY_KEY_CONFLICT",
}
